### ISSUE TITLE
Build packages also for the Alpine linux

### ISSUE THREAD

**Issue by pschiffe** [kha7iq/subvars#12]
What do you think about building packages also for the Alpine linux? It seems that `nfpms` does support it, just by adding `apk` to the `formats` option.

**Comment by kha7iq** [comment]
I am alright with it, if you have some time and would like to open another PR i will merge it.
Also if you are opening another PR it will be great to remove the publisher block https://github.com/kha7iq/subvars/blob/master/.goreleaser.yaml#L92 . 

Once these changes are merged i will create a new release
